version: '3'

services:

  localhost:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsApi
    ports:
      - "3306:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"